# aws_region     = "eu-west-1"
aws_region     = "eu-central-1"
environment    = "stg"
bucket_name    = "devops-michel-tf-statefile-eu-central-1"
dynamodb_table = "tf-state-locks"
vpc_name       = "michel_vpc"